version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5671:5671
        - 15671:15671
        - 5672:5672
        - 15672:15672
        - 25672:2567
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment: 
        - RABBITMQ_DEFAULT_USER=guest 
        - RABBITMQ_DEFAULT_PASS=guest
networks:
  rabbitmq_go_net:
    driver: bridge